routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

use App\Appointment;
// use Mail;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/testDemo', function () {
    // $name        = "vivek";
    // $mobile      = "7828161459";
    // $time        = "12.22";
    // $course_name = "mind power";
    $appointmentDetail = Appointment::where('id', 120)->first();
    $name              = $appointmentDetail->name;
    $mobile            = $appointmentDetail->mobile;
    $time              = $appointmentDetail->appointment_time;
    $time              = date(' h:i A | l | d-m-Y', strtotime($time));
// die;
    // $time = "12 nov 2019";
    // Mail::to("vivek.et1993@gmail.com")->queue(new AppointmentEmail($name, $mobile, $time));
    // Mail::to("socialselleracademy@gmail.com")->queue(new AppointmentEmail($name, $mobile, $time));

    // Mail::to("vivek.et1993@gmail.com")->queue(new AppointmentEmail($name, $mobile, $time));
    // Mail::to("socialselleracademy@gmail.com")->queue(new BuyCourse($name, $course_name));
    // Mail::to("socialselleracademy@gmail.com")->queue(new UnblockSupplier($name));
    // Mail::to("socialselleracademy@gmail.com")->queue(new ConsultBooking($name));
    // Mail::to('vivek.et1993@gmail.com')->send(new NewUserRegistration("vivek"));
    echo "success";

});
Route::get('artisan/clear-all', function () {
    \Artisan::call('config:cache');
});

Route::get('/payment-initiate', function () {
    return view('admin_panel/coupan/create');
});
Route::post('/payment-initiate-request', 'RazorpayController@create_order_id_razorpay');
Route::post('/payment_complete', 'RazorpayController@add_payment_request');

Route::get('admin/login', 'AdminLoginController@admin_login');
Route::post('admin/login', 'AdminLoginController@login_auth');
Route::get('admin/forgot_password', 'AdminLoginController@forgot_password');
Route::post('admin/forgot_password', 'AdminLoginController@send_mail_to_id');
Route::get('admin/reset_password/{token}', 'AdminLoginController@reset_password_page')->name('reset_password_page');
Route::post('admin/submit_reset_password', 'AdminLoginController@submit_reset_password');
Route::get('admin/user_profile', 'AdminController@user_profile');
Route::post('admin/update_password', 'AdminController@update_password');
Route::post('admin/check_password', 'AdminController@check_password');

Route::get('admin/logout', 'LoginController@logout');

Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'AdminHomeController@dashboard');
    Route::get('courses', 'CourseController@index');
    Route::post('add_course', 'CourseController@store_course');
    Route::get('add_course', 'CourseController@add_course');
    Route::post('update_course', 'CourseController@update_course');
    Route::post('change_status_course', 'CourseController@change_status_course');
    Route::get('course/edit/{course_id}', 'CourseController@edit_course');
    Route::get('lessons/{id}', 'CourseController@view_lesson');
    Route::post('modify_lesson', 'CourseController@add_lesson');
    Route::get('registered_users', 'AdminUserController@registered_users');
    Route::get('enrolled_users', 'AdminUserController@enrolled_users');
    Route::get('user_details/{user_id}', 'AdminUserController@user_details');
    Route::post('assign_course_to_student', 'AdminUserController@assign_course_to_student');

    Route::get('supplier_categories', 'CategoryController@supplier_category_list');
    Route::post('add_supplier_category', 'CategoryController@add_supplier_category');
    Route::post('edit_supplier_category', 'CategoryController@edit_supplier_category');

    Route::get('categories', 'CategoryController@index');
    Route::post('add_category', 'CategoryController@add_category');
    Route::post('edit_category', 'CategoryController@edit_category');
    Route::get('services', 'ServiceController@index');

    Route::post('add_service', 'ServiceController@add_service');
    Route::post('edit_service', 'ServiceController@edit_service');
    Route::get('blogs', 'BlogController@index');

    Route::post('add_blog', 'BlogController@add_blog');
    Route::post('edit_blog', 'BlogController@edit_blog');
    Route::post('delete_blog', 'BlogController@delete_blog');

    Route::get('appointment_video', 'AppointmentVideoController@index');

    Route::post('add_appointment_video', 'AppointmentVideoController@add_appointment_video');
    Route::post('edit_appointment_video', 'AppointmentVideoController@edit_appointment_video');
    Route::post('delete_appointment_video', 'AppointmentVideoController@delete_appointment_video');
    Route::get('suppliers', 'SupplierController@index');
    Route::get('edit_supplier/{id}', 'SupplierController@edit_supplier');
    Route::post('update_supplier', 'SupplierController@update_supplier');
    Route::post('delete_supplier_group_member', 'SupplierController@delete_supplier_group_member');
    Route::get('buy_suppliers_details', 'SupplierController@buy_suppliers_details');
    Route::post('add_supplier', 'SupplierController@store_supplier');
    Route::post('edit_supplier', 'SupplierController@edit_supplier');
    Route::get('add_supplier', 'SupplierController@add_supplier');
    Route::post('change_status_supplier', 'SupplierController@change_status_supplier');

    Route::get('payment_details/{num}', 'RazorpayController@payment_details');
    Route::get('settings', 'CountController@settings');
    Route::post('settings', 'CountController@update_settings');
    Route::get('appointments', 'AppointmentController@index');

    #course for
    Route::get('who_can_learn', 'AdminHomeController@who_can_learn_list');
    Route::get('who_can_learn/create', 'AdminHomeController@who_can_learn_create');
    Route::post('who_can_learn/create', 'AdminHomeController@who_can_learn_store');
    Route::get('seller_feedbacks', 'SellerFeedbackController@index');
    Route::post('add_seller_feedbacks', 'SellerFeedbackController@store_seller_feedback');
    Route::post('seller_feedback_delete', 'SellerFeedbackController@seller_feedback_delete');
    Route::get('whatsapp_record', 'AdminHomeController@whatsapp_mobile_list');
    Route::post('export_csv', 'AdminHomeController@export_csv');
    Route::get('export_csv_emails', 'AdminHomeController@export_csv_emails');

    Route::get('logout', 'AdminLoginController@logout');

});
Route::get('buy_suppliers_details_request_generate/{supplier_id}', 'SupplierController@buy_suppliers_details_request_generate');
Route::post('buy_suppliers_details', 'SupplierController@buy_suppliers_details');
Route::post('free_supplier_subscribe', 'SupplierController@free_supplier_suscribe');
Route::post('add_whatsapp_mobile', 'AdminHomeController@add_whatsapp_mobile');

Route::get('auth/google', 'SocialController@redirectToGoogle');
Route::get('auth/google/callback', 'SocialController@handleGoogleCallback');
Route::get('paywithrazorpay', 'RazorpayController@payWithRazorpay')->name('paywithrazorpay');
Route::get('success_payment', 'RazorpayController@success_page');
Route::get('auth/facebook', 'SocialController@redirectToFacebook');
Route::get('auth/facebook/callback', 'SocialController@handleFacebookCallback');

// Post Route For Makw Payment Request
// Route::post('payment', 'RazorpayController@payment')->name('payment');
// Route::post('payment-initiate-request', 'RazorpayController@payment')->name('payment');

###website routes

Route::get('login', 'WebsiteController@login');
Route::post('login', 'LoginController@signin');
// Route::get('login/{path}/{id}', 'WebsiteController@login');
Route::get('feedback', 'WebsiteController@feedback');
Route::get('privacy_policy', 'WebsiteController@privacy_policy');
Route::get('terms_condition', 'WebsiteController@terms_condition');
Route::get('data_deletion_url', 'WebsiteController@data_deletion_url');
Route::get('logout', 'LoginController@logout');
Route::get('my_courses', 'UserController@my_courses');
Route::get('/', 'WebsiteController@home');
Route::get('login_with_password', 'WebsiteController@login_with_password');
Route::get('signup', 'WebsiteController@signup');
Route::post('signup', 'LoginController@signup_process');

Route::get('dashboard', 'UserController@dashboard')->middleware('checkLogin');
Route::get('supplier_detail/{supplier_id}', 'UserController@supplier_detail');
Route::get('suppliers', 'UserController@my_suppliers');
Route::get('forgot_password', 'WebsiteController@forgot_password');
Route::any('reset_password', 'WebsiteController@reset_password');
Route::post('set_new_password', 'WebsiteController@set_new_password');
Route::get('all_suppliers', 'WebsiteController@all_suppliers');
Route::get('profile', 'UserController@profile')->middleware('checkLogin');
Route::post('profile_update', 'UserController@profile_update')->middleware('checkLogin');
Route::get('download_certificate/{course_id}', 'CourseController@certificate_download')->middleware('checkLogin');
Route::get('course_details/{id}', 'WebsiteController@course_details');
Route::get('course_enroll', 'WebsiteController@course_enroll');
Route::get('user_course_details/{id}', 'WebsiteController@user_course_details')->middleware('checkLogin');
Route::get('free_courses', 'WebsiteController@free_courses');
Route::get('free_videos', 'WebsiteController@free_videos');
Route::get('courses', 'WebsiteController@courses');
Route::get('appointment', 'WebsiteController@appointment');
Route::post('appointment', 'RazorpayController@generate_appointment');
Route::post('add_payment_request_for_appointment', 'RazorpayController@add_payment_request_for_appointment');

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    protected $guarded = [];
    public function getImageAttribute($value)
    {
        if ($value == null) {
            return $value;
        } else {
            return url($value);
        }

    }
}

resources/views/website/all_courses.blade.php
<!DOCTYPE html>
<html>
   <head>
      <title>Socialseller</title>
      @include('website.head')
   </head>
   <body>

      @include('website.partial.header')


      <section class="courses ">
      	<section class="pt-5 text-center">
         <div class="container">
            <div class="row  justify-content-center">

               	<div class="sectionheading pt-5 text-center">
                  <h3 class="dark-blue-text">Best Online Courses</h3>
                  <p class="subheading">These Courses will help you Grow your Online Business</p>
               </div>

            </div>
         </div>
      </section>
         <div class="container-fluid">
            <div class="row  justify-content-center">
                @foreach($courses as $row)
            <div class="col-12 col-md-3" data-aos="fade-up" data-aos-delay='0'>

                  <div class="coursecard">
                     <div class="courseimg">
                        @if(isset($row->image))
                        <img class="img-fluid" src="{{ $row->image }}" />
                        @endif
                        <span class="badge badge-warning">{{ $row->name }}</span>
                     </div>
                     <div class="p-2 coursedetails">
                        <span class="coursename">{{ $row->title }}</span>
                        <div class="clearfix"></div>
                        <div class="coursehighlights">
                           <img src="{{ asset('socialseller/images/Icon_5.png')}}" style="width: 20px;">
                           <p>{{ $row->total_lesson }} Lessons</p>
                        </div>
                        <div class="coursehighlights">
                           <!-- <img src="{{ asset('socialseller/images/Icon_6.png')}}" style="width: 20px;"> -->
                           @if($row->is_certificate==0)
                            <i class="fas fa-certificate" style='color:#d4eefe'></i>
                                            <p><del>Certificate</del></p>
                                            @else
                                            <i class="fas fa-certificate" style=''></i>
                                            <p>Certificate</p>
                                            @endif

                        </div>
                        <div class="coursehighlights">
                           <img src="{{ asset('socialseller/images/Icon_7.png')}}" style="width: 20px;">
                           <p>{{ $row->total_hours }} Hours</p>
                        </div>
                        <div class="clearfix"></div>
                     </div>
                     <a href="{{ url('course_details').'/'.$row->id }}" class="enrollbtn"><i class="fas fa-user-plus"></i>Enroll Now</a>
                  </div>
               </div>
             @endforeach


         </div>
      </section>


   @include ('website.footer')
      <div class="bsnav-mobile">
         <div class="bsnav-mobile-overlay">
         <div class="navbar">
            <div class="masterbarmobile"></div>
         </div>
      </div>

      @include ('website.footer-scripts')
   </body>
</html>

resources/views/website/consultation.blade.php
 <section  style="padding:4rem 0 4rem;">
         <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-6 text-center">
                  <img src="{{ asset('socialseller/images/consult.png')}} "
                     class="img-fluid "  data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500">
               </div>
               <div class="col-md-6 ">
                  <h1 class="dark-blue-text">
                     Take Professional Consultation
                  </h1>
                  <p>Are you caught up in the dilemma of what you like and what you dislike as a career option? Are you having difficulty in understanding what you should or shouldn't do? Our experienced career counsellors will show you the way to your dreams. Get in touch with us and clear this dilemma.</p>
                  <h5>Don’t worry, we are here to help!</h5>
                  <a href="{{url('appointment')}}" class=" green-btn btn text-white ml-0" style=" border-radius: 5px !important;font-size: 1.1rem !important;"> BOOK APPOINTMENT</a>
               </div>
            </div>
         </div>
      </section>

resources/views/website/enrollinside.blade.php
<style type="text/css">
  .department-tab2 {
    padding: 5px 15px;
    transition: 0.2s;
    text-align: left;
    box-shadow: 0px 4px 10px rgb(0 0 0 / 8%);
    margin: 0px 0 20px;
}
.department-tabs2  {
    display: flex;
    justify-content: center;
    flex-direction: column;

    margin: 15px;
    background-color: #ffffff;
}
.department-tab2-number {
    font-size: 32px;
    line-height: 1em;
    font-weight: 600;
    font-family: "Poppins", serif;
    color: #3368c6;
}
.department-tab2-decor {
    width: 33px;
    height: 3px;
    background-color: #3368c6;
}
.department-tab2-decor:not(:first-child) {
    margin-top: 15px;
}
.department-tab2.active, .department-tab2:hover {
    background-color: #3368c6;
    color: #ffffff;
    }
     .department-tab2.active .department-tab2-number, .department-tab2.active .department-tab2-text, .department-tab2:hover .department-tab2-number, .department-tab2:hover .department-tab2-text {
      color: #ffffff; }
    .department-tab2.active .department-tab2-decor, .department-tab2:hover .department-tab2-decor {
      background-color: #ffffff; }
  .double-title {
  position: relative; }
  .double-title span {
    position: relative;
    z-index: 1; }

.double-title:after {
  position: absolute;
  z-index: 0;
  right: 0;
  left: -0.05em;
  top: -.65em;
  font-size: 120px;
  line-height: 1em;
  white-space: nowrap;
  content: attr(data-title);
  color: #f7f9fb; }
  @media (max-width: 1229px) {
    .double-title:after {
      font-size: 100px; } }
  @media (max-width: 575px) {
    .double-title:after {
      font-size: 70px; } }

.bg-title {
  font-size: 120px;
  line-height: 1em;
  white-space: nowrap;
  content: attr(data-title);
  color: #ffffff; }
  @media (max-width: 1229px) {
    .bg-title {
      font-size: 100px; } }
  @media (max-width: 1229px) {
    .bg-title {
      margin-bottom: -.75em; } }
  @media (max-width: 575px) {
    .bg-title {
      font-size: 70px; } }
  .bg-title + * {
    position: relative;
    margin-top: -60px; }

.double-title--white:after {
  color: #ffffff; }

.double-title--vcenter:after {
  top: -.36em; }

.double-title--center:after {
  right: auto;
  left: 50%;
  transform: translateX(-50%); }

@media (min-width: 1230px) {
  .text-lg-left .double-title:after {
    left: -0.2em; } }
@media (max-width: 1229px) {
  .text-lg-left .double-title:after {
    left: 0; } }
@media (max-width: 1229px) {
  .double-title--center-lg:after {
    right: auto;
    left: 50%;
    transform: translateX(-50%); } }
.double-title--left:after {
  left: -0.2em; }

.double-title--right:after {
  left: auto;
  right: -0.2em; }
  @media (max-width: 1229px) {
    .double-title--right:after {
      right: auto;
      left: 50%;
      transform: translateX(-50%); } }

.double-title--top:after {
  left: -0.2em;
  top: -.76em; }

.double-title--top-md:after {
  left: -0.2em;
  top: -.76em; }
</style>
 <section class="py-5">

    <div class="container">
		<div class="text-center">
			<h3 class="dark-blue-text">How to Enroll inside the Course?</h3>
			<p class="subheading"> जानिये कैसे online course को ख़रीदा जाता है</p>
		</div>
        <div class="row text-center pt-4">
            <div class="col-12 col-md-6 mb-3">
               <div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/X0dNH9hjs_I?controls=0" allowfullscreen></iframe>
</div>
               
               
            </div>

            <div class="col-12 col-md-6">
                <div class="row">
                    <div class="col-md-6">

                        <div class="department-tab2">
                            <div class="department-tab2-number">1</div>
                            <div class="department-tab2-text">Check out the Course Intro Videos and Lessons</div>
                            <div class="department-tab2-decor"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="department-tab2">
                            <div class="department-tab2-number">2</div>
                            <div class="department-tab2-text">Click on Enroll Button and Create your Account on Socialseller  </div>
                            <div class="department-tab2-decor"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="department-tab2">
                            <div class="department-tab2-number">3</div>
                            <div class="department-tab2-text"> Complete the Payment and Tutorial Videos will be open to watch. </div>
                            <div class="department-tab2-decor"></div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="department-tab2">
                            <div class="department-tab2-number">4</div>
                            <div class="department-tab2-text">Complete the Course and Download your Completion Certificate.</div>
                            <div class="department-tab2-decor"></div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

    </div>
</section>

resources/views/website/feedback.blade.php
<section  style="padding: 4rem 0 4rem; background: #f3f9fd;">
         <div class="sectionheading text-center">
            <h3 class="dark-blue-text">Online Seller's Feedback
            </h3>
            <p class="subheading">आखिर क्या कहना है हमारे बारे मैं लोगो का ?</p>
         </div>
         <div class="container">
			<div>
				<div class="Online_Feedback owl-carousel owl-theme">
					<div class="item">
						<img src="{{ asset('socialseller/images/0001.jpg')}}" width="100%">
					</div>
					<div class="item">
						<img src="{{ asset('socialseller/images/0002.jpg')}}" width="100%">
					</div>
					<div class="item">
						<img src="{{ asset('socialseller/images/0003.jpg')}}" width="100%">
					</div>
					<div class="item">
						<img src="{{ asset('socialseller/images/0004.jpg')}}" width="100%">
					</div>
					<div class="item">
						<img src="{{ asset('socialseller/images/Content Reviews.png')}}" width="100%">
					</div>
				</div>
			</div>
         </div>
      </section>

<script>
$(document).ready(function(){
	$('.Online_Feedback').owlCarousel({
		center: true,
		items:2,
		loop:true,
		margin:10,
		responsive:{
			0:{
				items:1
			},
			600:{
				items:3
			},
			1000:{
				items:5
			}
		}
	});
});
</script>
<!--section  style="padding: 4rem 0 4rem; background: #f3f9fd;">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
			<img src="{{ asset('socialseller/images/0001.jpg')}}" width="100%">
		</div>
		<div class="col-md-3">
			<img src="{{ asset('socialseller/images/0002.jpg')}}" width="100%">
		</div>
		<div class="col-md-3">
			<img src="{{ asset('socialseller/images/0003.jpg')}}" width="100%">
		</div>
		<div class="col-md-3">
			<img src="{{ asset('socialseller/images/0004.jpg')}}" width="100%">
		</div>
		</div>
	</div>
</section-->

resources/views/website/footer-scripts.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.2/aos.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/js/swiper.min.js"></script>

<script src="https://cdn.jsdelivr.net/gh/fitodac/bsnav@master/dist/bsnav.min.js"></script>
<script src="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/owl.carousel.js"></script>

<script>
AOS.init();
$('.navbar-toggler').click(function() {
    $('.bsnav-mobile .navbar .masterbarmobile').html($(".masterbar").html());
});
$('#experienceModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget); // Button that triggered the modal
    var heading = button.data('heading'); // Extract info from data-* attributes
    var subheading = button.data('subheading'); // Extract info from data-* attributes
    var enqtype = button.data('enqtype'); // Extract info from data-* attributes
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this);
    modal.find('.modal-title').text(heading);
    modal.find('#expmodalsubtitle').text(subheading);
    modal.find('#hfenqtype').val(enqtype);
})
</script>
<script>
$('.owl-carousel').owlCarousel({
    merge: true,
    loop: true,
    margin: 10,
    video: true,
    nav: true,
    lazyLoad: true,
    bullet: true,
    responsive: {
        0: {
            items: 1,
            nav: true
        },
        600: {
            items: 2,
            nav: false
        },
        1000: {
            items: 3,
            nav: true,
            loop: false
        }
    }
})
</script>

resources/views/website/helping.blade.php
   <section  style="padding:4rem 0 4rem;">
         <div class="container">
            <div class="row justify-content-center">
               <div class="col-md-12 text-center">
                  <h1 class="dark-blue-text">
                     Socialseller Helping people to Start their own<br/> Online Business
                  </h1>
                     <p>Resellers and Online seller Trust Us</p>
               </div>
            </div>
            <div class="row pt-5">
               <div class="col-md-2 col-6">
                  <div class="text-center  border-radius " >
                     <img src="{{ asset('socialseller/images/Reseller.png')}} "
                     class="" data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500" style="width:50% !important;">
                     <br/>
                     <div><br/>
                        <h6><b>{{ $count->resellers }}</b></h6>
                        <h6 style="color:#0f54b2;">Reseller</h6>
                     </div>
                  </div>
               </div>
               <div class="col-md-2 col-6">
                  <div class="text-center  border-radius " >
                     <img src="{{ asset('socialseller/images/connect11.png')}} "
                     class="" data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500" style="width:50% !important;">
                     <br/><br/>
                     <h6><b>{{ $count->connects }}</b></h6>
                     <h6 style="color:#0f54b2;">Connects</h6>
                     
                  </div>
               </div>
               <div class="col-md-2 col-6">
                  <div class="text-center  border-radius " >
                    <img src="{{ asset('socialseller/images/wholesaler.png')}} "
                     class="" data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500" style="width:40% !important;">
                     <br/><br/>
                     <h6 ><b>{{ $count->suppliers }}</b></h6>
                        <h6  style="color:#0f54b2;">Suppliers</h6>
                  </div>
               </div>
               <div class="col-md-2 col-6">
                  <div class="text-center  border-radius" >
                    <img src="{{ asset('socialseller/images/Studentd.png')}} "
                     class="" data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500" style="width:40% !important;">
                      <br/><br/>
                     <h6><b>{{ $count->students }}</b></h6>
                        <h6  style="color:#0f54b2;">Students</h6>
                     
                  </div>
               </div>
                  <div class="col-md-2 col-6">
                  <div class="text-center  border-radius " >
                     <img src="{{ asset('socialseller/images/Views.png')}} "
                     class="" data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500" style="width:50% !important;">
                     <br/>
                     <div><br/>
                        <h6><b>{{ $count->views }}</b></h6>
                        <h6 style="color:#0f54b2;">Views</h6>
                     </div>
                  </div>
               </div>
               <div class="col-md-2 col-6">
                  <div class="text-center  border-radius " >
                     <img src="{{ asset('socialseller/images/Sunscriber.png')}} "
                     class="" data-aos="zoom-in" data-aos-delay="500" data-aos-duration="500" style="width:40% !important;">
                     <br/><br/>
                     <h6><b>{{ $count->subscriber  }}</b></h6>
                     <h6 style="color:#0f54b2;">Subscribers</h6>
                     
                  </div>
               </div>
            </div>

               
            <div class="row pt-5">
            
              
            </div>
         </div>
      </section>